# Generated by Django 5.2.8 on 2026-02-18 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=120, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('gravidade', models.CharField(choices=[('green', 'Verde'), ('yellow', 'Amarelo'), ('orange', 'Laranja'), ('red', 'Vermelho')], default='green', max_length=10)),
                ('dataInicio', models.DateTimeField()),
                ('dataFim', models.DateTimeField()),
                ('idAreaAviso', models.CharField(blank=True, max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
            },
        ),
        migrations.CreateModel(
            name='IncidenteAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('dico', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('created_at_api', models.DateTimeField(blank=True, null=True)),
                ('updated_at_api', models.DateTimeField(blank=True, null=True)),
                ('means_aerial', models.PositiveIntegerField(default=0)),
                ('means_aquatic', models.PositiveIntegerField(default=0)),
                ('means_man', models.PositiveIntegerField(default=0)),
                ('means_terrain', models.PositiveIntegerField(default=0)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('parish', models.CharField(blank=True, max_length=200, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('subregion', models.CharField(blank=True, max_length=200, null=True)),
                ('coords_ok', models.BooleanField(db_index=True, default=False)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('is_fire', models.BooleanField(default=False)),
                ('is_accident', models.BooleanField(default=False)),
                ('is_meteo', models.BooleanField(default=False)),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status_color', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('natureza_code', models.CharField(blank=True, max_length=20, null=True)),
                ('natureza', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('kml', models.TextField(blank=True, null=True)),
                ('significant', models.BooleanField(default=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('icnf_altitude', models.IntegerField(default=0)),
                ('icnf_fogacho', models.BooleanField(default=False)),
                ('icnf_fonte_alerta', models.CharField(blank=True, max_length=200, null=True)),
                ('burned_area', models.CharField(blank=True, max_length=50, null=True)),
                ('burned_area_agricultural', models.CharField(blank=True, max_length=50, null=True)),
                ('burned_area_bush', models.CharField(blank=True, max_length=50, null=True)),
                ('burned_area_forest', models.CharField(blank=True, max_length=50, null=True)),
                ('fire_duration', models.IntegerField(default=0)),
                ('burned_area_created_at', models.CharField(blank=True, max_length=50, null=True)),
                ('burned_area_updated_at', models.CharField(blank=True, max_length=50, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Incidente (API)',
                'verbose_name_plural': 'Incidentes (API)',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('IncidenteAPI', 'Incidente (API)'), ('Aviso', 'Aviso')], max_length=15)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='UsersProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_utilizador', models.CharField(choices=[('admin', 'Administrador'), ('utilizador', 'Utilizador')], default='utilizador', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Utilizador',
                'verbose_name_plural': 'Perfis de Utilizador',
            },
        ),
        migrations.CreateModel(
            name='NearbyAirbase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('distance', models.CharField(blank=True, max_length=50, null=True)),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_airbases', to='core.incidenteapi')),
            ],
            options={
                'verbose_name': 'Base Aérea Próxima',
                'verbose_name_plural': 'Bases Aéreas Próximas',
                'indexes': [models.Index(fields=['incidente'], name='core_nearby_inciden_2053a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='NearbyEmergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('distance', models.CharField(blank=True, max_length=50, null=True)),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_emergencies', to='core.incidenteapi')),
            ],
            options={
                'verbose_name': 'Emergência Próxima',
                'verbose_name_plural': 'Emergências Próximas',
                'indexes': [models.Index(fields=['incidente'], name='core_nearby_inciden_3f152a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NearbyFireStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('distance', models.CharField(blank=True, max_length=50, null=True)),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_fire_stations', to='core.incidenteapi')),
            ],
            options={
                'verbose_name': 'Bombeiros Próximos',
                'verbose_name_plural': 'Bombeiros Próximos',
                'indexes': [models.Index(fields=['incidente', 'name'], name='core_nearby_inciden_9b3f64_idx')],
            },
        ),
    ]
