# Generated by Django 5.2.8 on 2026-03-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenteapi',
            name='coords_ok',
        ),
        migrations.AddField(
            model_name='incidenteapi',
            name='finished_at_api',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidenteapi',
            name='means_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incidenteapi',
            name='weather_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incidenteapi',
            name='weather_humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidenteapi',
            name='weather_pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidenteapi',
            name='weather_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidenteapi',
            name='weather_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidenteapi',
            name='weather_wind',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='incidenteapi',
            index=models.Index(fields=['api_id'], name='core_incide_api_id_1562fd_idx'),
        ),
        migrations.AddIndex(
            model_name='incidenteapi',
            index=models.Index(fields=['active'], name='core_incide_active_f60df7_idx'),
        ),
        migrations.AddIndex(
            model_name='incidenteapi',
            index=models.Index(fields=['category'], name='core_incide_categor_2e7591_idx'),
        ),
        migrations.AddIndex(
            model_name='incidenteapi',
            index=models.Index(fields=['district'], name='core_incide_distric_72ca6e_idx'),
        ),
        migrations.AddIndex(
            model_name='incidenteapi',
            index=models.Index(fields=['county'], name='core_incide_county_9d7153_idx'),
        ),
    ]
