# Generated by Django 5.2.8 on 2026-03-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_incidenteapi_coords_ok_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('decir', models.CharField(blank=True, max_length=50, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Recurso Aéreo',
                'verbose_name_plural': 'Recursos Aéreos',
            },
        ),
        migrations.CreateModel(
            name='Bombero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('foundation_date', models.DateField(blank=True, null=True)),
                ('code_cb', models.CharField(blank=True, max_length=20, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bombeiro / Departamento',
                'verbose_name_plural': 'Bombeiros / Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('standbyTimesUrl', models.URLField(blank=True, null=True)),
                ('shareStandbyTimes', models.CharField(blank=True, max_length=10, null=True)),
                ('hasCTH', models.CharField(blank=True, max_length=10, null=True)),
                ('hasSIGLIC', models.CharField(blank=True, max_length=10, null=True)),
                ('hasEmergency', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True, null=True)),
                ('pilot', models.CharField(blank=True, max_length=10, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitais',
            },
        ),
        migrations.RemoveIndex(
            model_name='incidenteapi',
            name='core_incide_api_id_1562fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='incidenteapi',
            name='core_incide_active_f60df7_idx',
        ),
        migrations.RemoveIndex(
            model_name='incidenteapi',
            name='core_incide_categor_2e7591_idx',
        ),
        migrations.RemoveIndex(
            model_name='incidenteapi',
            name='core_incide_distric_72ca6e_idx',
        ),
        migrations.RemoveIndex(
            model_name='incidenteapi',
            name='core_incide_county_9d7153_idx',
        ),
        migrations.RemoveIndex(
            model_name='nearbyairbase',
            name='core_nearby_inciden_2053a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='nearbyemergency',
            name='core_nearby_inciden_3f152a_idx',
        ),
        migrations.RemoveIndex(
            model_name='nearbyfirestation',
            name='core_nearby_inciden_9b3f64_idx',
        ),
        migrations.RemoveField(
            model_name='incidenteapi',
            name='finished_at_api',
        ),
        migrations.RemoveField(
            model_name='incidenteapi',
            name='means_total',
        ),
        migrations.RemoveField(
            model_name='incidenteapi',
            name='weather_description',
        ),
        migrations.RemoveField(
            model_name='incidenteapi',
            name='weather_humidity',
        ),
        migrations.RemoveField(
            model_name='incidenteapi',
            name='weather_pressure',
        ),
        migrations.RemoveField(
            model_name='incidenteapi',
            name='weather_temperature',
        ),
        migrations.RemoveField(
            model_name='incidenteapi',
            name='weather_updated_at',
        ),
        migrations.RemoveField(
            model_name='incidenteapi',
            name='weather_wind',
        ),
        migrations.AddField(
            model_name='incidenteapi',
            name='coords_ok',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='incidenteapi',
            name='status_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
