# Generated by Django 5.2.8 on 2026-03-19 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_airresource_bombero_hospital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(blank=True, max_length=100, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('temperature_min_c', models.FloatField(blank=True, null=True)),
                ('temperature_max_c', models.FloatField(blank=True, null=True)),
                ('humidity_percent', models.IntegerField(blank=True, null=True)),
                ('wind_kmh', models.FloatField(blank=True, null=True)),
                ('precipitation_mmh', models.FloatField(blank=True, null=True)),
                ('pressure_hpa', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('wind_degree', models.IntegerField(blank=True, null=True)),
                ('wind_cardinal', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('incidente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='core.incidenteapi')),
            ],
        ),
    ]
