# Generated by Django 5.2.8 on 2026-04-02 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_weather'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'verbose_name': 'Tempo', 'verbose_name_plural': 'Tempo'},
        ),
        migrations.CreateModel(
            name='Feadback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sugestao', 'Sugestão'), ('bug', 'Bug'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('pagina', models.CharField(blank=True, choices=[('home', 'Página Inicial'), ('doacoes', 'Doações'), ('perfil', 'Perfil'), ('informacao', 'Informação'), ('avisos', 'Avisos'), ('precaucoes', 'Precauções'), ('tabela', 'Tabela de Incidentes'), ('login', 'Login'), ('registo', 'Registo'), ('sobre', 'Sobre'), ('editar_perfil', 'Editar Perfil')], max_length=50, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
