# Generated by Django 5.2.8 on 2026-04-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_weather_options_feadback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feadback',
            name='tipo',
            field=models.CharField(choices=[('default', '---------'), ('sugestao', 'Sugestão'), ('bug', 'Bug'), ('outro', 'Outro')], default='default', max_length=20),
        ),
    ]
