# Generated by Django 5.2.8 on 2026-04-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_feadback_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenteapi',
            name='api_id',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
