# Generated by Django 5.2.8 on 2026-04-06 09:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_incidenteapi_api_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feadback',
            new_name='Feedback',
        ),
    ]
