# Generated by Django 5.2.8 on 2026-04-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_feadback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='AreaNome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
