# Generated by Django 5.2.8 on 2026-04-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aviso_areanome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='tipo',
            field=models.CharField(choices=[('', '---------'), ('sugestao', 'Sugestão'), ('bug', 'Bug'), ('outro', 'Outro')], max_length=20),
        ),
    ]
