# Generated by Django 5.2.8 on 2026-04-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_feedback_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nearbyemergency',
            name='incidente',
        ),
        migrations.RemoveField(
            model_name='nearbyfirestation',
            name='incidente',
        ),
        migrations.AlterModelOptions(
            name='airresource',
            options={},
        ),
        migrations.AlterModelOptions(
            name='aviso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bombero',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notificacao',
            options={},
        ),
        migrations.RemoveField(
            model_name='airresource',
            name='decir',
        ),
        migrations.RemoveField(
            model_name='bombero',
            name='code_cb',
        ),
        migrations.RemoveField(
            model_name='bombero',
            name='foundation_date',
        ),
        migrations.RemoveField(
            model_name='bombero',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='bombero',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='hasCTH',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='hasEmergency',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='hasSIGLIC',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='pilot',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='shareStandbyTimes',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='standbyTimesUrl',
        ),
        migrations.AddField(
            model_name='incidenteapi',
            name='nearby_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tipo',
            field=models.CharField(choices=[('sugestao', 'Sugestão'), ('bug', 'Bug'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('IncidenteAPI', 'Incidente'), ('Aviso', 'Aviso')], max_length=15),
        ),
        migrations.DeleteModel(
            name='NearbyAirbase',
        ),
        migrations.DeleteModel(
            name='NearbyEmergency',
        ),
        migrations.DeleteModel(
            name='NearbyFireStation',
        ),
    ]
