# Generated by Django 5.2.8 on 2026-04-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_nearbyemergency_incidente_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bombero',
            new_name='Bombeiro',
        ),
    ]
