# Generated by Django 5.2.8 on 2026-05-05 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_bombero_bombeiro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersProfile',
        ),
    ]
